### PR TITLE
Allow newer versions of eslint when using npm version 2.

### PR DESCRIPTION
**Pull request by alexjeffburke**

### CODE REVIEW

**Comment by sunesimonsen** [comment]
Thanks

**Comment by sunesimonsen** [comment]
Released as v0.3.0

**Comment by sunesimonsen** [comment]
@alexjeffburke thinking about it, isn't this a bit too permissive. 

Wouldn't it be better to say:

```json
{
  "peerDependencies": {
    "eslint": "3 || 4"
  },
  ...
}
```

We don't really know if this configuration will be forward compatible forever.

**Comment by alexjeffburke** [comment]
@sunesimonsen hmm that's a fair point - I guess just a shame that it looses the specific version of eslint 3 that it was tested with. Btw, seems there is another npm 2 issue - I think the various plugins this requires need to be peerDependencies as well otherwise they don't seem to be put in the right place for them to be available to the top level. Shall I submit another couple of patches?

**Comment by sunesimonsen** [comment]
@alexjeffburke would you be up for another PR trying to get this working with npm 2. More peer dependencies is fine.

**Comment by sunesimonsen** [comment]
`^3.17.1 || 4` will do the job of not allowing earlier versions: https://semver.npmjs.com/

**Comment by alexjeffburke** [comment]
@sunesimonsen absolutely! I'll try to turn those around shortly :)

**Pull request merged**
