### PR TITLE
Further npm version 2 bits

### PR DESCRIPTION
**Pull request by alexjeffburke**
@sunesimonsen as we discussed - let me know if you want me to tweak these at all :)

### CODE REVIEW

**Review by sunesimonsen — COMMENTED** [review]
Maybe open up the plugin dependencies with ^ I think that would be safe.

**Comment by sunesimonsen** [comment]
Thanks

**Comment by sunesimonsen** [comment]
I released it as v1.0.0 as I don't really want any 0.* modules :-)

**Comment by alexjeffburke** [comment]
Haha no prob - I’ll try to make the amendment to the PR and repush today.

**Comment by sunesimonsen** [comment]
@alexjeffburke no need to do anything.

> Maybe open up the plugin dependencies with ^ I think that would be safe.

I didn't realise that it was actual dependencies and not peer dependencies.

**Comment by alexjeffburke** [comment]
I’m not sure this PR got merged in 1.0.0?

So, to be clear I’ll open up the peer dependencies woth ^ but should I leave the pure deps alone? :)

**Comment by sunesimonsen** [comment]
Don't we want the plugins to be peer dependencies, or is that necessary?

**Comment by alexjeffburke** [comment]
It’s necessary for the plugins to be installed at the right level for npm 2. The workaround I was using is add them to the parent project dependencies :)

**Comment by sunesimonsen** [comment]
@alexjeffburke what happens if they are both normal dependencies and peer dependencies?

It would be nice if npm 2+ didn't need to worry about this situation.

**Comment by sunesimonsen** [comment]
Damn I see you already did that 😊

**Comment by sunesimonsen** [comment]
Released as 1.1.0

**Pull request merged**
